# Generated by Django 5.1.3 on 2024-11-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=255)),
                ('agent_passport_id', models.CharField(max_length=50)),
                ('agent_passport_number', models.CharField(max_length=50)),
                ('agent_passport_date', models.DateField()),
            ],
            options={
                'db_table': 'agent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('agreement_id', models.AutoField(primary_key=True, serialize=False)),
                ('agreement_start_date', models.DateField()),
                ('agreement_end_date', models.DateField()),
                ('agreement_total_payments', models.FloatField()),
            ],
            options={
                'db_table': 'agreement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryPayment',
            fields=[
                ('category_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_amount', models.FloatField()),
            ],
            options={
                'db_table': 'category_payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_number', models.IntegerField()),
                ('company_full_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=255)),
                ('company_bank_number', models.CharField(max_length=50)),
                ('company_specialization', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_age', models.IntegerField()),
                ('employee_category', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeToAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'employee_to_agreement',
                'managed': False,
            },
        ),
    ]
